spring.application.name=Traveling

#db connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Enable CORS
spring.web.cors.allowed-origin-patterns=http://localhost:3000
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG